[env]
; Universal settings
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

; Matching baud rates arbitrarily
upload_speed = 9600
monitor_speed = 9600

; Unique "main.c" files assigned here for each device
[env:standard_variant]
; Child ESP-32 Module (B2)
build_src_filter = +</b2/main.c> -<.git/> -<.svn/>

[env:encoder_variant]
; Parent ESP-32 Module (B1), encoder attached
build_src_filter = +</b1/main.c> -<.git/> -<.svn/>

[env:display_variant]
; Child ESP-32 Module (B3), display attached
build_src_filter = +</b3/main.c> -<.git/> -<.svn/>

[env:adc_variant]
; Child ESP-32 Module (B4), analog to digital converter attached
build_src_filter = +</b4/main.c> -<.git/> -<.svn/>